package ch.inofix.portlet.contact.model.impl;

import ch.inofix.portlet.contact.model.Contact;
import ch.inofix.portlet.contact.model.ContactModel;
import ch.inofix.portlet.contact.model.ContactSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Contact service. Represents a row in the &quot;Inofix_Contact&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ch.inofix.portlet.contact.model.ContactModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContactImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContactImpl
 * @see ch.inofix.portlet.contact.model.Contact
 * @see ch.inofix.portlet.contact.model.ContactModel
 * @generated
 */
@JSON(strict = true)
public class ContactModelImpl extends BaseModelImpl<Contact>
    implements ContactModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a contact model instance should use the {@link ch.inofix.portlet.contact.model.Contact} interface instead.
     */
    public static final String TABLE_NAME = "Inofix_Contact";
    public static final Object[][] TABLE_COLUMNS = {
            { "uuid_", Types.VARCHAR },
            { "contactId", Types.BIGINT },
            { "groupId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "userName", Types.VARCHAR },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP },
            { "parentContactId", Types.BIGINT },
            { "card", Types.VARCHAR },
            { "uid", Types.VARCHAR },
            { "status", Types.INTEGER }
        };
    public static final String TABLE_SQL_CREATE = "create table Inofix_Contact (uuid_ VARCHAR(75) null,contactId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,parentContactId LONG,card TEXT null,uid VARCHAR(75) null,status INTEGER)";
    public static final String TABLE_SQL_DROP = "drop table Inofix_Contact";
    public static final String ORDER_BY_JPQL = " ORDER BY contact.contactId ASC";
    public static final String ORDER_BY_SQL = " ORDER BY Inofix_Contact.contactId ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.ch.inofix.portlet.contact.model.Contact"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.ch.inofix.portlet.contact.model.Contact"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.ch.inofix.portlet.contact.model.Contact"),
            true);
    public static long COMPANYID_COLUMN_BITMASK = 1L;
    public static long GROUPID_COLUMN_BITMASK = 2L;
    public static long UID_COLUMN_BITMASK = 4L;
    public static long UUID_COLUMN_BITMASK = 8L;
    public static long CONTACTID_COLUMN_BITMASK = 16L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.ch.inofix.portlet.contact.model.Contact"));
    private static ClassLoader _classLoader = Contact.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Contact.class
        };
    private String _uuid;
    private String _originalUuid;
    private long _contactId;
    private long _groupId;
    private long _originalGroupId;
    private boolean _setOriginalGroupId;
    private long _companyId;
    private long _originalCompanyId;
    private boolean _setOriginalCompanyId;
    private long _userId;
    private String _userUuid;
    private String _userName;
    private Date _createDate;
    private Date _modifiedDate;
    private long _parentContactId;
    private String _card;
    private String _uid;
    private String _originalUid;
    private int _status;
    private long _columnBitmask;
    private Contact _escapedModel;

    public ContactModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Contact toModel(ContactSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Contact model = new ContactImpl();

        model.setUuid(soapModel.getUuid());
        model.setContactId(soapModel.getContactId());
        model.setGroupId(soapModel.getGroupId());
        model.setCompanyId(soapModel.getCompanyId());
        model.setUserId(soapModel.getUserId());
        model.setUserName(soapModel.getUserName());
        model.setCreateDate(soapModel.getCreateDate());
        model.setModifiedDate(soapModel.getModifiedDate());
        model.setParentContactId(soapModel.getParentContactId());
        model.setCard(soapModel.getCard());
        model.setUid(soapModel.getUid());
        model.setStatus(soapModel.getStatus());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Contact> toModels(ContactSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Contact> models = new ArrayList<Contact>(soapModels.length);

        for (ContactSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _contactId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setContactId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _contactId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Contact.class;
    }

    @Override
    public String getModelClassName() {
        return Contact.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("uuid", getUuid());
        attributes.put("contactId", getContactId());
        attributes.put("groupId", getGroupId());
        attributes.put("companyId", getCompanyId());
        attributes.put("userId", getUserId());
        attributes.put("userName", getUserName());
        attributes.put("createDate", getCreateDate());
        attributes.put("modifiedDate", getModifiedDate());
        attributes.put("parentContactId", getParentContactId());
        attributes.put("card", getCard());
        attributes.put("uid", getUid());
        attributes.put("status", getStatus());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        String uuid = (String) attributes.get("uuid");

        if (uuid != null) {
            setUuid(uuid);
        }

        Long contactId = (Long) attributes.get("contactId");

        if (contactId != null) {
            setContactId(contactId);
        }

        Long groupId = (Long) attributes.get("groupId");

        if (groupId != null) {
            setGroupId(groupId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        String userName = (String) attributes.get("userName");

        if (userName != null) {
            setUserName(userName);
        }

        Date createDate = (Date) attributes.get("createDate");

        if (createDate != null) {
            setCreateDate(createDate);
        }

        Date modifiedDate = (Date) attributes.get("modifiedDate");

        if (modifiedDate != null) {
            setModifiedDate(modifiedDate);
        }

        Long parentContactId = (Long) attributes.get("parentContactId");

        if (parentContactId != null) {
            setParentContactId(parentContactId);
        }

        String card = (String) attributes.get("card");

        if (card != null) {
            setCard(card);
        }

        String uid = (String) attributes.get("uid");

        if (uid != null) {
            setUid(uid);
        }

        Integer status = (Integer) attributes.get("status");

        if (status != null) {
            setStatus(status);
        }
    }

    @JSON
    @Override
    public String getUuid() {
        if (_uuid == null) {
            return StringPool.BLANK;
        } else {
            return _uuid;
        }
    }

    @Override
    public void setUuid(String uuid) {
        if (_originalUuid == null) {
            _originalUuid = _uuid;
        }

        _uuid = uuid;
    }

    public String getOriginalUuid() {
        return GetterUtil.getString(_originalUuid);
    }

    @JSON
    @Override
    public long getContactId() {
        return _contactId;
    }

    @Override
    public void setContactId(long contactId) {
        _columnBitmask = -1L;

        _contactId = contactId;
    }

    @JSON
    @Override
    public long getGroupId() {
        return _groupId;
    }

    @Override
    public void setGroupId(long groupId) {
        _columnBitmask |= GROUPID_COLUMN_BITMASK;

        if (!_setOriginalGroupId) {
            _setOriginalGroupId = true;

            _originalGroupId = _groupId;
        }

        _groupId = groupId;
    }

    public long getOriginalGroupId() {
        return _originalGroupId;
    }

    @JSON
    @Override
    public long getCompanyId() {
        return _companyId;
    }

    @Override
    public void setCompanyId(long companyId) {
        _columnBitmask |= COMPANYID_COLUMN_BITMASK;

        if (!_setOriginalCompanyId) {
            _setOriginalCompanyId = true;

            _originalCompanyId = _companyId;
        }

        _companyId = companyId;
    }

    public long getOriginalCompanyId() {
        return _originalCompanyId;
    }

    @JSON
    @Override
    public long getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(long userId) {
        _userId = userId;
    }

    @Override
    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    @Override
    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @JSON
    @Override
    public String getUserName() {
        if (_userName == null) {
            return StringPool.BLANK;
        } else {
            return _userName;
        }
    }

    @Override
    public void setUserName(String userName) {
        _userName = userName;
    }

    @JSON
    @Override
    public Date getCreateDate() {
        return _createDate;
    }

    @Override
    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @JSON
    @Override
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    @Override
    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    @JSON
    @Override
    public long getParentContactId() {
        return _parentContactId;
    }

    @Override
    public void setParentContactId(long parentContactId) {
        _parentContactId = parentContactId;
    }

    @JSON
    @Override
    public String getCard() {
        if (_card == null) {
            return StringPool.BLANK;
        } else {
            return _card;
        }
    }

    @Override
    public void setCard(String card) {
        _card = card;
    }

    @JSON
    @Override
    public String getUid() {
        if (_uid == null) {
            return StringPool.BLANK;
        } else {
            return _uid;
        }
    }

    @Override
    public void setUid(String uid) {
        _columnBitmask |= UID_COLUMN_BITMASK;

        if (_originalUid == null) {
            _originalUid = _uid;
        }

        _uid = uid;
    }

    public String getOriginalUid() {
        return GetterUtil.getString(_originalUid);
    }

    @JSON
    @Override
    public int getStatus() {
        return _status;
    }

    @Override
    public void setStatus(int status) {
        _status = status;
    }

    @Override
    public StagedModelType getStagedModelType() {
        return new StagedModelType(PortalUtil.getClassNameId(
                Contact.class.getName()));
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            Contact.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Contact toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Contact) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        ContactImpl contactImpl = new ContactImpl();

        contactImpl.setUuid(getUuid());
        contactImpl.setContactId(getContactId());
        contactImpl.setGroupId(getGroupId());
        contactImpl.setCompanyId(getCompanyId());
        contactImpl.setUserId(getUserId());
        contactImpl.setUserName(getUserName());
        contactImpl.setCreateDate(getCreateDate());
        contactImpl.setModifiedDate(getModifiedDate());
        contactImpl.setParentContactId(getParentContactId());
        contactImpl.setCard(getCard());
        contactImpl.setUid(getUid());
        contactImpl.setStatus(getStatus());

        contactImpl.resetOriginalValues();

        return contactImpl;
    }

    @Override
    public int compareTo(Contact contact) {
        int value = 0;

        if (getContactId() < contact.getContactId()) {
            value = -1;
        } else if (getContactId() > contact.getContactId()) {
            value = 1;
        } else {
            value = 0;
        }

        if (value != 0) {
            return value;
        }

        return 0;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Contact)) {
            return false;
        }

        Contact contact = (Contact) obj;

        long primaryKey = contact.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        ContactModelImpl contactModelImpl = this;

        contactModelImpl._originalUuid = contactModelImpl._uuid;

        contactModelImpl._originalGroupId = contactModelImpl._groupId;

        contactModelImpl._setOriginalGroupId = false;

        contactModelImpl._originalCompanyId = contactModelImpl._companyId;

        contactModelImpl._setOriginalCompanyId = false;

        contactModelImpl._originalUid = contactModelImpl._uid;

        contactModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Contact> toCacheModel() {
        ContactCacheModel contactCacheModel = new ContactCacheModel();

        contactCacheModel.uuid = getUuid();

        String uuid = contactCacheModel.uuid;

        if ((uuid != null) && (uuid.length() == 0)) {
            contactCacheModel.uuid = null;
        }

        contactCacheModel.contactId = getContactId();

        contactCacheModel.groupId = getGroupId();

        contactCacheModel.companyId = getCompanyId();

        contactCacheModel.userId = getUserId();

        contactCacheModel.userName = getUserName();

        String userName = contactCacheModel.userName;

        if ((userName != null) && (userName.length() == 0)) {
            contactCacheModel.userName = null;
        }

        Date createDate = getCreateDate();

        if (createDate != null) {
            contactCacheModel.createDate = createDate.getTime();
        } else {
            contactCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            contactCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            contactCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        contactCacheModel.parentContactId = getParentContactId();

        contactCacheModel.card = getCard();

        String card = contactCacheModel.card;

        if ((card != null) && (card.length() == 0)) {
            contactCacheModel.card = null;
        }

        contactCacheModel.uid = getUid();

        String uid = contactCacheModel.uid;

        if ((uid != null) && (uid.length() == 0)) {
            contactCacheModel.uid = null;
        }

        contactCacheModel.status = getStatus();

        return contactCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(25);

        sb.append("{uuid=");
        sb.append(getUuid());
        sb.append(", contactId=");
        sb.append(getContactId());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", userName=");
        sb.append(getUserName());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append(", parentContactId=");
        sb.append(getParentContactId());
        sb.append(", card=");
        sb.append(getCard());
        sb.append(", uid=");
        sb.append(getUid());
        sb.append(", status=");
        sb.append(getStatus());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(40);

        sb.append("<model><model-name>");
        sb.append("ch.inofix.portlet.contact.model.Contact");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>uuid</column-name><column-value><![CDATA[");
        sb.append(getUuid());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>contactId</column-name><column-value><![CDATA[");
        sb.append(getContactId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userName</column-name><column-value><![CDATA[");
        sb.append(getUserName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>parentContactId</column-name><column-value><![CDATA[");
        sb.append(getParentContactId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>card</column-name><column-value><![CDATA[");
        sb.append(getCard());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>uid</column-name><column-value><![CDATA[");
        sb.append(getUid());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>status</column-name><column-value><![CDATA[");
        sb.append(getStatus());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
