package ch.inofix.portlet.contact.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Contact service. Represents a row in the &quot;Inofix_Contact&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ch.inofix.portlet.contact.model.impl.ContactModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ch.inofix.portlet.contact.model.impl.ContactImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Contact
 * @see ch.inofix.portlet.contact.model.impl.ContactImpl
 * @see ch.inofix.portlet.contact.model.impl.ContactModelImpl
 * @generated
 */
public interface ContactModel extends BaseModel<Contact>, StagedGroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a contact model instance should use the {@link Contact} interface instead.
     */

    /**
     * Returns the primary key of this contact.
     *
     * @return the primary key of this contact
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this contact.
     *
     * @param primaryKey the primary key of this contact
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this contact.
     *
     * @return the uuid of this contact
     */
    @AutoEscape
    @Override
    public String getUuid();

    /**
     * Sets the uuid of this contact.
     *
     * @param uuid the uuid of this contact
     */
    @Override
    public void setUuid(String uuid);

    /**
     * Returns the contact ID of this contact.
     *
     * @return the contact ID of this contact
     */
    public long getContactId();

    /**
     * Sets the contact ID of this contact.
     *
     * @param contactId the contact ID of this contact
     */
    public void setContactId(long contactId);

    /**
     * Returns the group ID of this contact.
     *
     * @return the group ID of this contact
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this contact.
     *
     * @param groupId the group ID of this contact
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this contact.
     *
     * @return the company ID of this contact
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this contact.
     *
     * @param companyId the company ID of this contact
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this contact.
     *
     * @return the user ID of this contact
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this contact.
     *
     * @param userId the user ID of this contact
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this contact.
     *
     * @return the user uuid of this contact
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this contact.
     *
     * @param userUuid the user uuid of this contact
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this contact.
     *
     * @return the user name of this contact
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this contact.
     *
     * @param userName the user name of this contact
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this contact.
     *
     * @return the create date of this contact
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this contact.
     *
     * @param createDate the create date of this contact
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this contact.
     *
     * @return the modified date of this contact
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this contact.
     *
     * @param modifiedDate the modified date of this contact
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the parent contact ID of this contact.
     *
     * @return the parent contact ID of this contact
     */
    public long getParentContactId();

    /**
     * Sets the parent contact ID of this contact.
     *
     * @param parentContactId the parent contact ID of this contact
     */
    public void setParentContactId(long parentContactId);

    /**
     * Returns the card of this contact.
     *
     * @return the card of this contact
     */
    @AutoEscape
    public String getCard();

    /**
     * Sets the card of this contact.
     *
     * @param card the card of this contact
     */
    public void setCard(String card);

    /**
     * Returns the uid of this contact.
     *
     * @return the uid of this contact
     */
    @AutoEscape
    public String getUid();

    /**
     * Sets the uid of this contact.
     *
     * @param uid the uid of this contact
     */
    public void setUid(String uid);

    /**
     * Returns the status of this contact.
     *
     * @return the status of this contact
     */
    public int getStatus();

    /**
     * Sets the status of this contact.
     *
     * @param status the status of this contact
     */
    public void setStatus(int status);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(ch.inofix.portlet.contact.model.Contact contact);

    @Override
    public int hashCode();

    @Override
    public CacheModel<ch.inofix.portlet.contact.model.Contact> toCacheModel();

    @Override
    public ch.inofix.portlet.contact.model.Contact toEscapedModel();

    @Override
    public ch.inofix.portlet.contact.model.Contact toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
